version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hiring_db
    ports:
      - "5432:5432"
    networks:
      - hiring-network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    image: api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - auth-service
      - user-service
      - job-service
      - company-service
      - application-service
    networks:
      - hiring-network

  auth-service:
    build: ./auth_service
    container_name: auth-service
    env_file:
      - ./auth_service/.env.docker
    depends_on:
      - postgres
    networks:
      - hiring-network

  user-service:
    build: ./user_service
    container_name: user-service
    env_file:
      - ./user_service/.env.docker
    depends_on:
      - postgres
    networks:
      - hiring-network

  job-service:
    build: ./job_service
    container_name: job-service
    env_file:
      - ./job_service/.env.docker
    depends_on:
      - postgres
    networks:
      - hiring-network

  company-service:
    build: ./company_service
    container_name: company-service
    env_file:
      - ./company_service/.env.docker
    depends_on:
      - postgres
    networks:
      - hiring-network

  application-service:
    build: ./application_service
    container_name: application-service
    env_file:
      - ./application_service/.env.docker
    depends_on:
      - postgres
    networks:
      - hiring-network

networks:
  hiring-network:
    driver: bridge