version: "3.9"

services:

  db:
    image: postgres:15
    container_name: company-postgres
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: companydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - company-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sa"]
      interval: 5s
      timeout: 5s
      retries: 5

  company-service:
    build: .
    container_name: company-service
    ports:
      - "8003:8003"
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy   # âœ… THIS IS THE FIX
    restart: always
    networks:
      - company-network

volumes:
  postgres_data:

networks:
  company-network: