version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: company-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: company_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - company-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  company-service:
    build: .
    container_name: company-service
    ports:
      - "8003:8003"
    env_file:
      - .env.docker
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    networks:
      - company-network

volumes:
  postgres_data:

networks:
  company-network: