version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: job-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: job_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - job-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  job-service:
    build: .
    container_name: job-service
    ports:
      - "8004:8004"
    env_file:
      - .env.docker
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    networks:
      - job-network

volumes:
  postgres_data:

networks:
  job-network: